/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoPost = IDL.Record({
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'likeCount' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'commentCount' : IDL.Nat,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const User = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});
export const Comment = IDL.Record({
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'videoId' : IDL.Nat,
});
export const Notification = IDL.Record({
  'notificationType' : IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'follow' : IDL.Null,
  }),
  'read' : IDL.Bool,
  'fromUser' : IDL.Principal,
  'videoId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPagedVideos' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(VideoPost)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(VideoPost)], ['query']),
  'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(VideoPost)], ['query']),
  'getVideosByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoPost)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Nat], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([User], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoPost)], ['query']),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikeVideo' : IDL.Func([IDL.Nat], [], []),
  'updateUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoPost = IDL.Record({
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'likeCount' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'commentCount' : IDL.Nat,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const User = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'videoId' : IDL.Nat,
  });
  const Notification = IDL.Record({
    'notificationType' : IDL.Variant({
      'like' : IDL.Null,
      'comment' : IDL.Null,
      'follow' : IDL.Null,
    }),
    'read' : IDL.Bool,
    'fromUser' : IDL.Principal,
    'videoId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPagedVideos' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(VideoPost)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(VideoPost)], ['query']),
    'getVideosByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VideoPost)],
        ['query'],
      ),
    'getVideosByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoPost)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Nat], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([User], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoPost)], ['query']),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikeVideo' : IDL.Func([IDL.Nat], [], []),
    'updateUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };